/**
 * data.js — Mock catalog shaped like future Supabase tables.
 * No real brand/product names — placeholders only until you wire the API.
 *
 * Suggested Supabase tables (map 1:1 later):
 *   categories, brands (optional), supplements, supplement_macros,
 *   supplement_actives, supplement_allergens, supplement_lab_tests,
 *   supplement_scores_cache (optional)
 */

const CATEGORIES = [
  {
    id: 'whey',
    name: 'Protein Powders',
    short: 'Whey / milk-based protein',
    icon: '🥤',
    color: '#0d9488',
    description:
      'Compare isolate, concentrate, hydrolysate, and casein on protein per scoop, purity, lactose, sugars, and cost efficiency.',
    whatWeScore: [
      'Protein grams per scoop',
      'Protein % of serving (purity)',
      'Added sugar',
      'Sodium & fillers',
      'Cost per gram of protein',
      'Allergen fit vs your prefs',
      'Lab testing / label accuracy',
    ],
  },
  {
    id: 'plant',
    name: 'Plant Protein',
    short: 'Pea, rice, hemp & blends',
    icon: '🌿',
    color: '#16a34a',
    description:
      'Plant powders scored on protein density, completeness proxies, sodium (common issue), fillers, and allergen profile.',
    whatWeScore: [
      'Protein per scoop',
      'Protein purity %',
      'Sodium load',
      'Added sugar & fillers',
      'Soy / gluten allergen flags',
      'Cost per gram protein',
      'Third-party testing',
    ],
  },
  {
    id: 'creatine',
    name: 'Creatine',
    short: 'Monohydrate & blends',
    icon: '⚡',
    color: '#2563eb',
    description:
      'Creatine is about dose honesty and purity — 3–5g monohydrate, minimal fillers, no sugar-loaded “delivery” blends unless you want them.',
    whatWeScore: [
      'Creatine dose per serving',
      'Purity / filler %',
      'Added sugar',
      'Cost per effective dose',
      'Form (mono vs blend)',
      'Lab testing',
    ],
  },
  {
    id: 'gainer',
    name: 'Mass Gainers',
    short: 'High-calorie formulas',
    icon: '📦',
    color: '#d97706',
    description:
      'Gainers trade purity for calories. We score protein density, added sugar, allergen load, and whether it fits a bulking vs cutting goal.',
    whatWeScore: [
      'Calories & protein per serving',
      'Protein % of serving',
      'Added sugar',
      'Fillers & maltodextrin proxies',
      'Allergen stack',
      'Cost per gram protein',
      'Goal fit',
    ],
  },
  {
    id: 'amino',
    name: 'BCAA / Aminos',
    short: 'BCAA, EAA & recovery aminos',
    icon: '💧',
    color: '#7c3aed',
    description:
      'Amino products scored on active amino grams, filler ratio, artificial sweeteners, and cost per gram of actives.',
    whatWeScore: [
      'Active amino dose',
      'Filler %',
      'Added sugar',
      'Artificial sweetener flags',
      'Cost per serving',
      'Lab testing',
    ],
  },
  {
    id: 'collagen',
    name: 'Collagen',
    short: 'Peptides & blends',
    icon: '✨',
    color: '#db2777',
    description:
      'Collagen isn’t a complete muscle protein — we score peptide dose, fillers/flavors, sugars, and transparency.',
    whatWeScore: [
      'Collagen peptides per scoop',
      'Fillers & flavor load',
      'Added sugar',
      'Sodium',
      'Cost per gram collagen',
      'Lab testing',
    ],
  },
  {
    id: 'pre',
    name: 'Pre-Workout',
    short: 'Stim & stim-free pumps',
    icon: '🔥',
    color: '#e11d48',
    description:
      'Pre-workouts scored on disclosed actives (citrulline, caffeine), proprietary-blend opacity, sugar, and stim transparency.',
    whatWeScore: [
      'Citrulline dose',
      'Caffeine disclosure',
      'Proprietary blend penalty',
      'Added sugar & artificials',
      'Sodium',
      'Lab testing',
      'Goal / stim preference fit',
    ],
  },
  {
    id: 'omega',
    name: 'Omega-3',
    short: 'Fish / algae oil',
    icon: '🐟',
    color: '#0891b2',
    description:
      'Omega-3s scored on EPA+DHA per serving, oxidation risk proxies, fillers, and cost per gram of combined EPA/DHA.',
    whatWeScore: [
      'EPA + DHA dose',
      'Form (TG vs ethyl ester proxy)',
      'Fillers',
      'Cost per gram EPA+DHA',
      'Allergen (fish) flags',
      'Lab / purity claims',
    ],
  },
  {
    id: 'multi',
    name: 'Multivitamins',
    short: 'Daily multi formulas',
    icon: '💊',
    color: '#ca8a04',
    description:
      'Multis are hard to score perfectly — we focus on unnecessary sugar, artificials, allergen fillers, and transparency of doses.',
    whatWeScore: [
      'Active vitamin transparency',
      'Added sugar',
      'Artificial colors / fillers',
      'Allergen fit',
      'Cost per daily serving',
      'Lab testing',
    ],
  },
];

/** Generic manufacturer placeholders — replace with brands table later */
const BRAND_PLACEHOLDERS = [
  'Brand TBD-A',
  'Brand TBD-B',
  'Brand TBD-C',
  'Brand TBD-D',
  'Brand TBD-E',
  'Brand TBD-F',
  'Brand TBD-G',
  'Brand TBD-H',
];

/**
 * Factory helpers keep entries consistent with a future DB row shape.
 */
function baseEntry(partial) {
  return {
    // identity
    id: partial.id,
    slug: partial.id,
    code: partial.code, // e.g. WP-01 — display name until real names exist
    name: partial.name, // generic: "Whey Isolate Entry 01"
    brand: partial.brand || 'Brand TBD',
    category: partial.category,
    subcategory: partial.subcategory || '',
    form: partial.form || 'powder', // powder | capsule | softgel | tablet | liquid
    typeLabel: partial.typeLabel,
    icon: partial.icon,
    summary: partial.summary || '',
    // serving / package
    servingSizeG: partial.servingSizeG,
    servingLabel: partial.servingLabel || `per ${partial.servingSizeG}g serving`,
    servingsPerContainer: partial.servingsPerContainer,
    packageSizeG: partial.packageSizeG || partial.defaultPackageG,
    defaultPackageG: partial.defaultPackageG || partial.packageSizeG,
    // macros (per serving)
    calories: partial.calories ?? 0,
    protein: partial.protein ?? 0,
    carbs: partial.carbs ?? 0,
    fat: partial.fat ?? 0,
    fiber: partial.fiber ?? 0,
    sugar: partial.sugar ?? 0,
    addedSugar: partial.addedSugar ?? 0,
    sodiumMg: partial.sodiumMg ?? 0,
    potassiumMg: partial.potassiumMg ?? 0,
    calciumMg: partial.calciumMg ?? 0,
    cholesterolMg: partial.cholesterolMg ?? 0,
    // actives
    activeDoseG: partial.activeDoseG ?? partial.protein ?? 0,
    activeName: partial.activeName || 'Active',
    actives: partial.actives || [], // [{ name, amount, unit }]
    aminoProfile: partial.aminoProfile || null, // { leucine, isoleucine, valine, ... }
    // quality
    fillersPct: partial.fillersPct ?? 0,
    sweeteners: partial.sweeteners || [],
    thickeners: partial.thickeners || [],
    colors: partial.colors || [],
    proprietaryBlend: partial.proprietaryBlend ?? false,
    allergens: partial.allergens || [],
    artificial: partial.artificial ?? false,
    // lab / trust
    thirdPartyTested: partial.thirdPartyTested ?? false,
    labName: partial.labName || null,
    labelAccuracyPct: partial.labelAccuracyPct ?? null, // claimed vs tested protein etc.
    heavyMetalsPass: partial.heavyMetalsPass ?? null,
    // commerce (mock MSRP — user can override in UI)
    defaultPriceUSD: partial.defaultPriceUSD,
    pricePerServingUSD: partial.pricePerServingUSD ?? null,
    // guidance
    timing: partial.timing || '',
    howToUse: partial.howToUse || '',
    bestFor: partial.bestFor || [],
    avoidIf: partial.avoidIf || [],
    pros: partial.pros || [],
    cons: partial.cons || [],
    notes: partial.notes || '',
    // meta for supabase
    dataStatus: 'placeholder', // placeholder | verified | lab_pending
    updatedAt: partial.updatedAt || '2026-09-01',
  };
}

/* ==========================================================================
   RICH PLACEHOLDER CATALOG — expand freely; swap for Supabase select(*) later
   ========================================================================== */

const CATALOG = [
  // ——— WHEY / MILK PROTEIN (12) ———
  baseEntry({
    id: 'whey-01',
    code: 'WP-01',
    name: 'Whey Isolate Entry 01',
    brand: 'Brand TBD-A',
    category: 'whey',
    subcategory: 'isolate',
    typeLabel: 'Milk-based · Whey Protein Isolate',
    icon: '🥤',
    summary: 'High-purity isolate profile. Strong protein-per-scoop, near-zero sugar, light lactose residual.',
    servingSizeG: 30,
    servingLabel: 'per 30g scoop',
    servingsPerContainer: 30,
    defaultPackageG: 900,
    calories: 110,
    protein: 27,
    carbs: 1,
    fat: 0.4,
    fiber: 0,
    sugar: 0.5,
    addedSugar: 0,
    sodiumMg: 45,
    potassiumMg: 120,
    calciumMg: 80,
    cholesterolMg: 10,
    activeDoseG: 27,
    activeName: 'Protein',
    actives: [{ name: 'Whey protein isolate', amount: 27, unit: 'g' }],
    aminoProfile: { leucine: 2.7, isoleucine: 1.5, valine: 1.4, totalBcaa: 5.6 },
    fillersPct: 6,
    sweeteners: ['stevia'],
    thickeners: ['sunflower lecithin'],
    allergens: ['lactose'],
    artificial: false,
    thirdPartyTested: true,
    labName: 'Lab TBD',
    labelAccuracyPct: 98,
    heavyMetalsPass: true,
    defaultPriceUSD: 48,
    timing: 'Post-workout or between meals',
    howToUse: 'Mix 1 scoop in 250–300ml water or milk alternative.',
    bestFor: ['cutting', 'maintenance', 'high protein density'],
    avoidIf: ['severe lactose intolerance'],
    pros: ['High protein %', 'Low sugar', 'Lab tested'],
    cons: ['Still dairy-derived', 'Premium price'],
    notes: 'Placeholder entry — replace name/brand via Supabase.',
  }),
  baseEntry({
    id: 'whey-02',
    code: 'WP-02',
    name: 'Whey Concentrate Entry 02',
    brand: 'Brand TBD-B',
    category: 'whey',
    subcategory: 'concentrate',
    typeLabel: 'Milk-based · Whey Concentrate',
    icon: '🥤',
    summary: 'Budget concentrate. More carbs/fat/lactose; watch sodium and artificial sweeteners.',
    servingSizeG: 32,
    servingsPerContainer: 31,
    defaultPackageG: 1000,
    calories: 130,
    protein: 24,
    carbs: 3.5,
    fat: 2,
    sugar: 2.2,
    addedSugar: 1.5,
    sodiumMg: 160,
    potassiumMg: 140,
    calciumMg: 110,
    cholesterolMg: 45,
    activeDoseG: 24,
    activeName: 'Protein',
    actives: [{ name: 'Whey protein concentrate', amount: 24, unit: 'g' }],
    aminoProfile: { leucine: 2.3, isoleucine: 1.3, valine: 1.2, totalBcaa: 4.8 },
    fillersPct: 18,
    sweeteners: ['sucralose', 'acesulfame potassium'],
    thickeners: ['xanthan gum', 'soy lecithin'],
    colors: ['artificial color'],
    allergens: ['lactose', 'soy'],
    artificial: true,
    thirdPartyTested: false,
    labelAccuracyPct: 91,
    heavyMetalsPass: null,
    defaultPriceUSD: 32,
    timing: 'Post-workout',
    howToUse: '1 scoop in 200–250ml liquid.',
    bestFor: ['bulking', 'budget protein'],
    avoidIf: ['lactose allergy', 'avoid artificial sweeteners'],
    pros: ['Lower price', 'Decent protein'],
    cons: ['Higher fillers', 'Artificial sweeteners', 'Not lab verified'],
  }),
  baseEntry({
    id: 'whey-03',
    code: 'WP-03',
    name: 'Casein Entry 03',
    brand: 'Brand TBD-C',
    category: 'whey',
    subcategory: 'casein',
    typeLabel: 'Milk-based · Micellar Casein',
    icon: '🌙',
    summary: 'Slow-digesting casein for overnight coverage. Moderate purity, lactose present.',
    servingSizeG: 34,
    servingsPerContainer: 26,
    defaultPackageG: 900,
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1,
    sugar: 1.5,
    addedSugar: 0,
    sodiumMg: 90,
    calciumMg: 400,
    cholesterolMg: 20,
    activeDoseG: 24,
    activeName: 'Protein',
    actives: [{ name: 'Micellar casein', amount: 24, unit: 'g' }],
    aminoProfile: { leucine: 2.2, isoleucine: 1.2, valine: 1.3, totalBcaa: 4.7 },
    fillersPct: 12,
    sweeteners: ['stevia'],
    thickeners: ['guar gum'],
    allergens: ['lactose'],
    artificial: false,
    thirdPartyTested: true,
    labName: 'Lab TBD',
    labelAccuracyPct: 96,
    heavyMetalsPass: true,
    defaultPriceUSD: 42,
    timing: 'Before bed',
    howToUse: '1 scoop in 300ml liquid; thicker mix.',
    bestFor: ['overnight protein', 'maintenance'],
    avoidIf: ['lactose intolerance'],
    pros: ['Slow release', 'High calcium'],
    cons: ['Not ideal intra-workout', 'Dairy allergen'],
  }),
  baseEntry({
    id: 'whey-04',
    code: 'WP-04',
    name: 'Hydrolyzed Whey Entry 04',
    brand: 'Brand TBD-A',
    category: 'whey',
    subcategory: 'hydrolysate',
    typeLabel: 'Milk-based · Hydrolyzed Isolate',
    icon: '🥤',
    summary: 'Pre-digested peptides for fast absorption. Excellent macros; premium cost.',
    servingSizeG: 28,
    servingsPerContainer: 32,
    defaultPackageG: 900,
    calories: 105,
    protein: 25,
    carbs: 0.8,
    fat: 0.3,
    sugar: 0.3,
    addedSugar: 0,
    sodiumMg: 55,
    activeDoseG: 25,
    activeName: 'Protein',
    actives: [{ name: 'Hydrolyzed whey isolate', amount: 25, unit: 'g' }],
    aminoProfile: { leucine: 2.8, isoleucine: 1.6, valine: 1.5, totalBcaa: 5.9 },
    fillersPct: 5,
    sweeteners: ['monk fruit'],
    thickeners: ['sunflower lecithin'],
    allergens: ['lactose'],
    artificial: false,
    thirdPartyTested: true,
    labName: 'Lab TBD',
    labelAccuracyPct: 99,
    heavyMetalsPass: true,
    defaultPriceUSD: 56,
    timing: 'Immediately post-workout',
    howToUse: '1 scoop in water; mixes thin.',
    bestFor: ['cutting', 'fast absorption'],
    avoidIf: ['budget-limited'],
    pros: ['Fastest absorption', 'Very clean label'],
    cons: ['Expensive', 'Bitter notes possible'],
  }),
  baseEntry({
    id: 'whey-05',
    code: 'WP-05',
    name: 'Whey Blend Entry 05',
    brand: 'Brand TBD-D',
    category: 'whey',
    subcategory: 'blend',
    typeLabel: 'Milk-based · Isolate + Concentrate Blend',
    icon: '🥤',
    summary: 'Mid-tier blend. Balanced macros with moderate fillers and some soy lecithin.',
    servingSizeG: 31,
    servingsPerContainer: 28,
    defaultPackageG: 870,
    calories: 120,
    protein: 25,
    carbs: 2.5,
    fat: 1.2,
    sugar: 1.4,
    addedSugar: 0.5,
    sodiumMg: 110,
    activeDoseG: 25,
    activeName: 'Protein',
    actives: [
      { name: 'Whey isolate', amount: 15, unit: 'g' },
      { name: 'Whey concentrate', amount: 10, unit: 'g' },
    ],
    aminoProfile: { leucine: 2.5, isoleucine: 1.4, valine: 1.3, totalBcaa: 5.2 },
    fillersPct: 14,
    sweeteners: ['sucralose'],
    thickeners: ['soy lecithin'],
    allergens: ['lactose', 'soy'],
    artificial: true,
    thirdPartyTested: true,
    labelAccuracyPct: 94,
    heavyMetalsPass: true,
    defaultPriceUSD: 38,
    timing: 'Anytime protein gap',
    howToUse: '1 scoop shake.',
    bestFor: ['maintenance', 'general use'],
    avoidIf: ['soy allergy', 'strict clean-label'],
    pros: ['Balanced price/performance'],
    cons: ['Contains concentrate + soy'],
  }),
  baseEntry({
    id: 'whey-06',
    code: 'WP-06',
    name: 'Whey Isolate Entry 06',
    brand: 'Brand TBD-E',
    category: 'whey',
    subcategory: 'isolate',
    typeLabel: 'Milk-based · Whey Isolate (flavored)',
    icon: '🥤',
    summary: 'Flavored isolate with higher sweetener/thickener load — check sugar alcohols & sodium.',
    servingSizeG: 32,
    servingsPerContainer: 25,
    defaultPackageG: 800,
    calories: 120,
    protein: 25,
    carbs: 3,
    fat: 0.8,
    sugar: 1,
    addedSugar: 0,
    sodiumMg: 180,
    fiber: 1,
    activeDoseG: 25,
    activeName: 'Protein',
    actives: [{ name: 'Whey isolate', amount: 25, unit: 'g' }],
    aminoProfile: { leucine: 2.5, isoleucine: 1.4, valine: 1.4, totalBcaa: 5.3 },
    fillersPct: 16,
    sweeteners: ['sucralose', 'sugar alcohol'],
    thickeners: ['xanthan gum', 'cellulose gum'],
    colors: ['natural flavor only'],
    allergens: ['lactose'],
    artificial: true,
    thirdPartyTested: false,
    labelAccuracyPct: 92,
    defaultPriceUSD: 40,
    timing: 'Post-workout',
    howToUse: '1 scoop; foams more due to gums.',
    bestFor: ['taste-first users'],
    avoidIf: ['GI sensitive to sugar alcohols'],
    pros: ['Good taste profile (claimed)'],
    cons: ['Higher sodium', 'More gums', 'No lab seal'],
  }),
  baseEntry({
    id: 'whey-07',
    code: 'WP-07',
    name: 'Whey Concentrate Entry 07',
    brand: 'Brand TBD-F',
    category: 'whey',
    subcategory: 'concentrate',
    typeLabel: 'Milk-based · Whey Concentrate (unflavored)',
    icon: '🥤',
    summary: 'Unflavored concentrate — fewer additives, more lactose, flexible for cooking/baking.',
    servingSizeG: 30,
    servingsPerContainer: 33,
    defaultPackageG: 1000,
    calories: 120,
    protein: 23,
    carbs: 3,
    fat: 1.8,
    sugar: 2.5,
    addedSugar: 0,
    sodiumMg: 70,
    activeDoseG: 23,
    activeName: 'Protein',
    actives: [{ name: 'Whey concentrate', amount: 23, unit: 'g' }],
    aminoProfile: { leucine: 2.2, isoleucine: 1.2, valine: 1.1, totalBcaa: 4.5 },
    fillersPct: 8,
    sweeteners: [],
    thickeners: [],
    allergens: ['lactose'],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 97,
    heavyMetalsPass: true,
    defaultPriceUSD: 28,
    timing: 'Meals / recipes',
    howToUse: 'Mix into oats, yogurt, or shakes.',
    bestFor: ['cooking', 'budget', 'clean-label'],
    avoidIf: ['want ready-to-drink flavor'],
    pros: ['Minimal additives', 'Cheap'],
    cons: ['Lower protein %', 'Lactose'],
  }),
  baseEntry({
    id: 'whey-08',
    code: 'WP-08',
    name: 'Clear Whey Entry 08',
    brand: 'Brand TBD-B',
    category: 'whey',
    subcategory: 'isolate',
    typeLabel: 'Milk-based · Clear Whey Isolate',
    icon: '🥤',
    summary: 'Acidified clear whey. High protein, very low fat/carb; can be higher sodium.',
    servingSizeG: 25,
    servingsPerContainer: 20,
    defaultPackageG: 500,
    calories: 90,
    protein: 20,
    carbs: 0.5,
    fat: 0.1,
    sugar: 0.2,
    addedSugar: 0,
    sodiumMg: 200,
    activeDoseG: 20,
    activeName: 'Protein',
    actives: [{ name: 'Clear whey isolate', amount: 20, unit: 'g' }],
    aminoProfile: { leucine: 2.1, isoleucine: 1.2, valine: 1.1, totalBcaa: 4.4 },
    fillersPct: 10,
    sweeteners: ['sucralose'],
    thickeners: [],
    colors: ['citric acid system'],
    allergens: ['lactose'],
    artificial: true,
    thirdPartyTested: true,
    labelAccuracyPct: 95,
    heavyMetalsPass: true,
    defaultPriceUSD: 36,
    timing: 'Daytime / hot weather',
    howToUse: 'Shake hard with cold water; juice-like.',
    bestFor: ['cutting', 'low calorie'],
    avoidIf: ['high sodium restriction'],
    pros: ['Light texture', 'Low cal'],
    cons: ['Sodium', 'Artificial sweetener'],
  }),

  // ——— PLANT (8) ———
  baseEntry({
    id: 'plant-01',
    code: 'PP-01',
    name: 'Plant Protein Entry 01',
    brand: 'Brand TBD-C',
    category: 'plant',
    subcategory: 'blend',
    typeLabel: 'Plant · Pea + Rice Blend',
    icon: '🌿',
    summary: 'Common pea/rice blend. Watch sodium and grit; may include soy in some SKUs.',
    servingSizeG: 35,
    servingsPerContainer: 21,
    defaultPackageG: 750,
    calories: 140,
    protein: 22,
    carbs: 6,
    fat: 3,
    fiber: 2,
    sugar: 1,
    addedSugar: 0,
    sodiumMg: 280,
    activeDoseG: 22,
    activeName: 'Protein',
    actives: [
      { name: 'Pea protein', amount: 14, unit: 'g' },
      { name: 'Rice protein', amount: 8, unit: 'g' },
    ],
    aminoProfile: { leucine: 1.8, isoleucine: 1.0, valine: 1.1, totalBcaa: 3.9 },
    fillersPct: 22,
    sweeteners: ['sucralose'],
    thickeners: ['xanthan gum'],
    allergens: ['soy'],
    artificial: true,
    thirdPartyTested: false,
    labelAccuracyPct: 90,
    defaultPriceUSD: 38,
    timing: 'Post-workout / meal gap',
    howToUse: 'Blend 1 scoop; texture improves with blender.',
    bestFor: ['dairy-free'],
    avoidIf: ['soy allergy', 'low-sodium diet'],
    pros: ['Dairy-free'],
    cons: ['High sodium', 'Fillers', 'Artificial sweetener'],
  }),
  baseEntry({
    id: 'plant-02',
    code: 'PP-02',
    name: 'Pea Isolate Entry 02',
    brand: 'Brand TBD-A',
    category: 'plant',
    subcategory: 'pea',
    typeLabel: 'Plant · Pea Protein Isolate',
    icon: '🌱',
    summary: 'Cleaner pea isolate. Better purity, still elevated sodium vs whey isolate.',
    servingSizeG: 30,
    servingsPerContainer: 25,
    defaultPackageG: 750,
    calories: 120,
    protein: 24,
    carbs: 2,
    fat: 1.5,
    fiber: 1,
    sugar: 0,
    addedSugar: 0,
    sodiumMg: 190,
    activeDoseG: 24,
    activeName: 'Protein',
    actives: [{ name: 'Pea protein isolate', amount: 24, unit: 'g' }],
    aminoProfile: { leucine: 2.0, isoleucine: 1.1, valine: 1.2, totalBcaa: 4.3 },
    fillersPct: 10,
    sweeteners: ['stevia'],
    thickeners: ['sunflower lecithin'],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labName: 'Lab TBD',
    labelAccuracyPct: 96,
    heavyMetalsPass: true,
    defaultPriceUSD: 44,
    timing: 'Anytime',
    howToUse: '1 scoop in 300ml; shake well.',
    bestFor: ['vegan', 'clean-label', 'lactose-free'],
    avoidIf: [],
    pros: ['No major allergens', 'Lab tested', 'Zero added sugar'],
    cons: ['Earthy taste', 'Sodium still moderate'],
  }),
  baseEntry({
    id: 'plant-03',
    code: 'PP-03',
    name: 'Hemp Protein Entry 03',
    brand: 'Brand TBD-D',
    category: 'plant',
    subcategory: 'hemp',
    typeLabel: 'Plant · Hemp + Pumpkin',
    icon: '🌿',
    summary: 'Lower protein density, more fat/fiber. Whole-food style plant powder.',
    servingSizeG: 33,
    servingsPerContainer: 20,
    defaultPackageG: 660,
    calories: 145,
    protein: 20,
    carbs: 7,
    fat: 4.5,
    fiber: 4,
    sugar: 2,
    addedSugar: 1,
    sodiumMg: 120,
    activeDoseG: 20,
    activeName: 'Protein',
    actives: [
      { name: 'Hemp protein', amount: 12, unit: 'g' },
      { name: 'Pumpkin protein', amount: 8, unit: 'g' },
    ],
    aminoProfile: { leucine: 1.4, isoleucine: 0.8, valine: 0.9, totalBcaa: 3.1 },
    fillersPct: 15,
    sweeteners: ['coconut sugar'],
    thickeners: [],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 94,
    heavyMetalsPass: true,
    defaultPriceUSD: 40,
    timing: 'Meals / smoothies',
    howToUse: 'Blend into smoothie; not ideal as watery shake.',
    bestFor: ['whole-food preference'],
    avoidIf: ['need max protein per scoop'],
    pros: ['Fiber + fats', 'Clean'],
    cons: ['Lower protein', 'Some added sugar'],
  }),
  baseEntry({
    id: 'plant-04',
    code: 'PP-04',
    name: 'Soy Isolate Entry 04',
    brand: 'Brand TBD-E',
    category: 'plant',
    subcategory: 'soy',
    typeLabel: 'Plant · Soy Protein Isolate',
    icon: '🌱',
    summary: 'High protein soy isolate. Complete amino profile; soy allergen flag is critical.',
    servingSizeG: 30,
    servingsPerContainer: 30,
    defaultPackageG: 900,
    calories: 115,
    protein: 26,
    carbs: 1.5,
    fat: 0.5,
    sugar: 0.5,
    addedSugar: 0,
    sodiumMg: 220,
    activeDoseG: 26,
    activeName: 'Protein',
    actives: [{ name: 'Soy protein isolate', amount: 26, unit: 'g' }],
    aminoProfile: { leucine: 2.1, isoleucine: 1.3, valine: 1.3, totalBcaa: 4.7 },
    fillersPct: 8,
    sweeteners: ['stevia'],
    thickeners: ['soy lecithin'],
    allergens: ['soy'],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 97,
    heavyMetalsPass: true,
    defaultPriceUSD: 35,
    timing: 'Anytime',
    howToUse: '1 scoop shake.',
    bestFor: ['vegan', 'high protein'],
    avoidIf: ['soy allergy'],
    pros: ['Complete protein', 'High purity'],
    cons: ['Soy allergen', 'Sodium'],
  }),
  baseEntry({
    id: 'plant-05',
    code: 'PP-05',
    name: 'Plant Protein Entry 05',
    brand: 'Brand TBD-F',
    category: 'plant',
    subcategory: 'blend',
    typeLabel: 'Plant · Multi-source Blend',
    icon: '🌿',
    summary: 'Marketing-heavy blend with higher fillers and proprietary protein blend opacity.',
    servingSizeG: 36,
    servingsPerContainer: 18,
    defaultPackageG: 650,
    calories: 150,
    protein: 20,
    carbs: 8,
    fat: 3.5,
    fiber: 3,
    sugar: 3,
    addedSugar: 2,
    sodiumMg: 310,
    activeDoseG: 20,
    activeName: 'Protein',
    actives: [{ name: 'Proprietary plant blend', amount: 20, unit: 'g' }],
    fillersPct: 28,
    sweeteners: ['sucralose', 'acesulfame potassium'],
    thickeners: ['xanthan gum', 'guar gum'],
    colors: ['artificial color'],
    proprietaryBlend: true,
    allergens: ['soy', 'gluten'],
    artificial: true,
    thirdPartyTested: false,
    labelAccuracyPct: 85,
    defaultPriceUSD: 42,
    timing: 'Anytime',
    howToUse: '1 scoop.',
    bestFor: [],
    avoidIf: ['gluten', 'soy', 'clean-label'],
    pros: ['Wide flavoring'],
    cons: ['Opaque blend', 'High fillers', 'Allergens', 'Sugar'],
  }),

  // ——— CREATINE (8) ———
  baseEntry({
    id: 'creatine-01',
    code: 'CR-01',
    name: 'Creatine Monohydrate Entry 01',
    brand: 'Brand TBD-A',
    category: 'creatine',
    subcategory: 'monohydrate',
    typeLabel: 'Creatine · Micronized Monohydrate',
    icon: '⚡',
    summary: 'Standard 5g micronized mono. Gold-standard form, zero fillers.',
    servingSizeG: 5,
    servingsPerContainer: 60,
    defaultPackageG: 300,
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    sugar: 0,
    addedSugar: 0,
    sodiumMg: 0,
    activeDoseG: 5,
    activeName: 'Creatine Monohydrate',
    actives: [{ name: 'Creatine monohydrate', amount: 5, unit: 'g' }],
    fillersPct: 0,
    sweeteners: [],
    thickeners: [],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labName: 'Lab TBD',
    labelAccuracyPct: 99,
    heavyMetalsPass: true,
    defaultPriceUSD: 18,
    timing: 'Daily (any time)',
    howToUse: '5g daily in water; loading optional.',
    bestFor: ['bulking', 'cutting', 'strength'],
    avoidIf: [],
    pros: ['Pure', 'Cheap per dose', 'Evidence-backed form'],
    cons: ['Unflavored only'],
    notes: 'Preferred baseline creatine comparator.',
  }),
  baseEntry({
    id: 'creatine-02',
    code: 'CR-02',
    name: 'Creatine Monohydrate Entry 02',
    brand: 'Brand TBD-B',
    category: 'creatine',
    subcategory: 'monohydrate',
    typeLabel: 'Creatine · Creapure-style Mono',
    icon: '⚡',
    summary: 'Premium mono with stronger lab claims. Same 5g effective dose.',
    servingSizeG: 5,
    servingsPerContainer: 80,
    defaultPackageG: 400,
    calories: 0,
    activeDoseG: 5,
    activeName: 'Creatine Monohydrate',
    actives: [{ name: 'Creatine monohydrate (premium)', amount: 5, unit: 'g' }],
    fillersPct: 0,
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labName: 'Lab TBD',
    labelAccuracyPct: 99.5,
    heavyMetalsPass: true,
    defaultPriceUSD: 28,
    timing: 'Daily',
    howToUse: '5g / day.',
    bestFor: ['quality-first'],
    avoidIf: [],
    pros: ['Purity claims', 'More servings'],
    cons: ['Higher price than basic mono'],
  }),
  baseEntry({
    id: 'creatine-03',
    code: 'CR-03',
    name: 'Creatine Blend Entry 03',
    brand: 'Brand TBD-C',
    category: 'creatine',
    subcategory: 'blend',
    typeLabel: 'Creatine · Blend with dextrose',
    icon: '⚡',
    summary: 'Under-dosed creatine stacked with sugar. Weak dose honesty.',
    servingSizeG: 12,
    servingsPerContainer: 40,
    defaultPackageG: 480,
    calories: 35,
    carbs: 7,
    sugar: 6,
    addedSugar: 6,
    sodiumMg: 40,
    activeDoseG: 3,
    activeName: 'Creatine',
    actives: [
      { name: 'Creatine monohydrate', amount: 3, unit: 'g' },
      { name: 'Dextrose', amount: 6, unit: 'g' },
    ],
    fillersPct: 40,
    sweeteners: ['dextrose'],
    proprietaryBlend: false,
    allergens: [],
    artificial: true,
    thirdPartyTested: false,
    labelAccuracyPct: 88,
    defaultPriceUSD: 22,
    timing: 'Post-workout',
    howToUse: '1 scoop in water.',
    bestFor: [],
    avoidIf: ['low sugar preference', 'want full 5g dose'],
    pros: ['Flavored'],
    cons: ['Only 3g creatine', 'Added sugar', 'Fillers'],
  }),
  baseEntry({
    id: 'creatine-04',
    code: 'CR-04',
    name: 'Creatine HCl Entry 04',
    brand: 'Brand TBD-D',
    category: 'creatine',
    subcategory: 'hcl',
    typeLabel: 'Creatine · Hydrochloride',
    icon: '⚡',
    summary: 'HCl form marketed for solubility. Dose often lower; score on active grams.',
    servingSizeG: 2,
    servingsPerContainer: 90,
    defaultPackageG: 180,
    calories: 0,
    activeDoseG: 1.5,
    activeName: 'Creatine HCl',
    actives: [{ name: 'Creatine HCl', amount: 1.5, unit: 'g' }],
    fillersPct: 5,
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 95,
    heavyMetalsPass: true,
    defaultPriceUSD: 30,
    timing: 'Daily',
    howToUse: 'As labeled; compare active creatine to 5g mono.',
    bestFor: ['solubility preference'],
    avoidIf: ['want cheapest effective creatine'],
    pros: ['Mixes easily'],
    cons: ['Lower absolute creatine', 'Pricey per effective dose'],
  }),
  baseEntry({
    id: 'creatine-05',
    code: 'CR-05',
    name: 'Creatine Capsules Entry 05',
    brand: 'Brand TBD-E',
    category: 'creatine',
    subcategory: 'monohydrate',
    form: 'capsule',
    typeLabel: 'Creatine · Capsules',
    icon: '💊',
    summary: 'Capsule convenience. Check capsules needed to hit 5g.',
    servingSizeG: 5,
    servingLabel: 'per 6 capsules (~5g)',
    servingsPerContainer: 30,
    defaultPackageG: 150,
    calories: 5,
    activeDoseG: 5,
    activeName: 'Creatine Monohydrate',
    actives: [{ name: 'Creatine monohydrate', amount: 5, unit: 'g' }],
    fillersPct: 8,
    thickeners: ['capsule shell'],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 97,
    heavyMetalsPass: true,
    defaultPriceUSD: 25,
    timing: 'Daily',
    howToUse: '6 capsules with water.',
    bestFor: ['travel', 'no-powder'],
    avoidIf: ['hate pill burden'],
    pros: ['Portable'],
    cons: ['Many pills', 'Slightly more fillers'],
  }),
  baseEntry({
    id: 'creatine-06',
    code: 'CR-06',
    name: 'Creatine Gummy Entry 06',
    brand: 'Brand TBD-F',
    category: 'creatine',
    subcategory: 'gummy',
    form: 'gummy',
    typeLabel: 'Creatine · Gummies',
    icon: '⚡',
    summary: 'Gummy format usually under-doses and adds sugar — scrutinize active dose.',
    servingSizeG: 8,
    servingLabel: 'per 4 gummies',
    servingsPerContainer: 20,
    defaultPackageG: 160,
    calories: 40,
    carbs: 8,
    sugar: 6,
    addedSugar: 6,
    activeDoseG: 2,
    activeName: 'Creatine',
    actives: [{ name: 'Creatine monohydrate', amount: 2, unit: 'g' }],
    fillersPct: 55,
    sweeteners: ['sugar', 'glucose syrup'],
    colors: ['artificial color'],
    allergens: [],
    artificial: true,
    thirdPartyTested: false,
    labelAccuracyPct: 80,
    defaultPriceUSD: 32,
    timing: 'Daily',
    howToUse: '4 gummies.',
    bestFor: [],
    avoidIf: ['low sugar', 'need 5g dose'],
    pros: ['Convenient taste'],
    cons: ['Low dose', 'Sugar', 'Expensive per gram creatine'],
  }),

  // ——— MASS GAINERS (5) ———
  baseEntry({
    id: 'gainer-01',
    code: 'MG-01',
    name: 'Mass Gainer Entry 01',
    brand: 'Brand TBD-B',
    category: 'gainer',
    subcategory: 'high-sugar',
    typeLabel: 'Gainer · High-carb formula',
    icon: '📦',
    summary: 'Classic dirty gainer — huge calories, high maltodextrin/sugar, multi-allergen.',
    servingSizeG: 150,
    servingsPerContainer: 16,
    defaultPackageG: 2500,
    calories: 580,
    protein: 40,
    carbs: 90,
    fat: 8,
    fiber: 2,
    sugar: 18,
    addedSugar: 14,
    sodiumMg: 320,
    activeDoseG: 40,
    activeName: 'Protein',
    actives: [{ name: 'Protein blend', amount: 40, unit: 'g' }],
    fillersPct: 35,
    sweeteners: ['sugar', 'sucralose'],
    thickeners: ['maltodextrin'],
    allergens: ['lactose', 'gluten', 'soy'],
    artificial: true,
    thirdPartyTested: false,
    labelAccuracyPct: 88,
    defaultPriceUSD: 55,
    timing: 'Between meals / post-workout surplus',
    howToUse: '1 scoop with 400–500ml milk or water.',
    bestFor: ['hard bulking'],
    avoidIf: ['cutting', 'lactose', 'gluten', 'soy'],
    pros: ['Easy surplus calories'],
    cons: ['Sugar', 'Allergens', 'Low protein purity'],
  }),
  baseEntry({
    id: 'gainer-02',
    code: 'MG-02',
    name: 'Mass Gainer Entry 02',
    brand: 'Brand TBD-A',
    category: 'gainer',
    subcategory: 'clean',
    typeLabel: 'Gainer · Lower-sugar formula',
    icon: '📦',
    summary: 'Cleaner gainer profile — still calorie dense but better protein ratio & less sugar.',
    servingSizeG: 120,
    servingsPerContainer: 20,
    defaultPackageG: 2400,
    calories: 420,
    protein: 35,
    carbs: 60,
    fat: 5,
    fiber: 4,
    sugar: 4,
    addedSugar: 1,
    sodiumMg: 180,
    activeDoseG: 35,
    activeName: 'Protein',
    actives: [{ name: 'Whey + casein blend', amount: 35, unit: 'g' }],
    fillersPct: 18,
    sweeteners: ['stevia'],
    thickeners: ['oat flour'],
    allergens: ['lactose', 'gluten'],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 95,
    heavyMetalsPass: true,
    defaultPriceUSD: 62,
    timing: 'Bulking meals',
    howToUse: '1 scoop shake.',
    bestFor: ['bulking with better macros'],
    avoidIf: ['cutting', 'gluten-free needed'],
    pros: ['Better protein density', 'Lower sugar', 'Lab tested'],
    cons: ['Still gluten/dairy', 'Price'],
  }),
  baseEntry({
    id: 'gainer-03',
    code: 'MG-03',
    name: 'Mass Gainer Entry 03',
    brand: 'Brand TBD-C',
    category: 'gainer',
    subcategory: 'vegan',
    typeLabel: 'Gainer · Plant-based',
    icon: '📦',
    summary: 'Vegan gainer. Higher fiber/sodium; check complete protein and sugar.',
    servingSizeG: 130,
    servingsPerContainer: 15,
    defaultPackageG: 2000,
    calories: 500,
    protein: 32,
    carbs: 75,
    fat: 9,
    fiber: 8,
    sugar: 8,
    addedSugar: 3,
    sodiumMg: 290,
    activeDoseG: 32,
    activeName: 'Protein',
    actives: [{ name: 'Pea/rice protein', amount: 32, unit: 'g' }],
    fillersPct: 25,
    sweeteners: ['cane sugar', 'stevia'],
    thickeners: ['tapioca maltodextrin'],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 93,
    heavyMetalsPass: true,
    defaultPriceUSD: 58,
    timing: 'Bulking',
    howToUse: '1 scoop with plant milk.',
    bestFor: ['vegan bulking'],
    avoidIf: ['cutting'],
    pros: ['Dairy-free surplus'],
    cons: ['Sodium', 'Fiber GI load'],
  }),

  // ——— AMINOS (5) ———
  baseEntry({
    id: 'amino-01',
    code: 'AA-01',
    name: 'BCAA Entry 01',
    brand: 'Brand TBD-D',
    category: 'amino',
    subcategory: 'bcaa',
    typeLabel: 'BCAA · 2:1:1 Powder',
    icon: '💧',
    summary: 'Classic BCAA. Useful intra-workout for some; fillers & artificials common.',
    servingSizeG: 10,
    servingsPerContainer: 40,
    defaultPackageG: 400,
    calories: 10,
    protein: 5,
    activeDoseG: 5,
    activeName: 'BCAAs',
    actives: [
      { name: 'L-Leucine', amount: 2.5, unit: 'g' },
      { name: 'L-Isoleucine', amount: 1.25, unit: 'g' },
      { name: 'L-Valine', amount: 1.25, unit: 'g' },
    ],
    aminoProfile: { leucine: 2.5, isoleucine: 1.25, valine: 1.25, totalBcaa: 5 },
    fillersPct: 25,
    sweeteners: ['sucralose'],
    colors: ['artificial color'],
    allergens: [],
    artificial: true,
    thirdPartyTested: false,
    defaultPriceUSD: 28,
    timing: 'Intra-workout',
    howToUse: '1 scoop in water during training.',
    bestFor: ['fasted training (optional)'],
    avoidIf: ['avoid artificial sweeteners'],
    pros: ['Simple 2:1:1'],
    cons: ['Fillers', 'Artificials', 'Redundant if protein intake is high'],
  }),
  baseEntry({
    id: 'amino-02',
    code: 'AA-02',
    name: 'EAA Entry 02',
    brand: 'Brand TBD-A',
    category: 'amino',
    subcategory: 'eaa',
    typeLabel: 'EAA · Full spectrum',
    icon: '💧',
    summary: 'Full EAA profile with better active ratio and cleaner sweetener choice.',
    servingSizeG: 12,
    servingsPerContainer: 30,
    defaultPackageG: 360,
    calories: 15,
    protein: 8,
    activeDoseG: 8,
    activeName: 'EAAs',
    actives: [{ name: 'Essential amino acid blend', amount: 8, unit: 'g' }],
    aminoProfile: { leucine: 3.0, isoleucine: 1.5, valine: 1.5, totalBcaa: 6 },
    fillersPct: 12,
    sweeteners: ['stevia'],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 96,
    heavyMetalsPass: true,
    defaultPriceUSD: 36,
    timing: 'Intra / between meals',
    howToUse: '1 scoop.',
    bestFor: ['low-calorie amino support'],
    avoidIf: [],
    pros: ['Full EAAs', 'Cleaner label', 'Lab tested'],
    cons: ['Price'],
  }),
  baseEntry({
    id: 'amino-03',
    code: 'AA-03',
    name: 'EAA Entry 03',
    brand: 'Brand TBD-E',
    category: 'amino',
    subcategory: 'eaa',
    typeLabel: 'EAA · Proprietary blend',
    icon: '💧',
    summary: 'Opaque proprietary amino blend — harder to trust dose transparency.',
    servingSizeG: 11,
    servingsPerContainer: 30,
    defaultPackageG: 330,
    calories: 20,
    protein: 6,
    sugar: 1,
    addedSugar: 1,
    activeDoseG: 6,
    activeName: 'Amino blend',
    actives: [{ name: 'Proprietary EAA blend', amount: 6, unit: 'g' }],
    fillersPct: 30,
    sweeteners: ['sucralose', 'acesulfame potassium'],
    proprietaryBlend: true,
    allergens: [],
    artificial: true,
    thirdPartyTested: false,
    defaultPriceUSD: 33,
    timing: 'Intra-workout',
    howToUse: '1 scoop.',
    bestFor: [],
    avoidIf: ['want dose transparency'],
    pros: ['Flavored'],
    cons: ['Proprietary', 'Fillers', 'Artificials'],
  }),

  // ——— COLLAGEN (4) ———
  baseEntry({
    id: 'collagen-01',
    code: 'CO-01',
    name: 'Collagen Peptides Entry 01',
    brand: 'Brand TBD-A',
    category: 'collagen',
    subcategory: 'bovine',
    typeLabel: 'Collagen · Bovine peptides (unflavored)',
    icon: '✨',
    summary: 'Unflavored peptides. Good dose, minimal extras — not a complete muscle protein.',
    servingSizeG: 11,
    servingsPerContainer: 40,
    defaultPackageG: 450,
    calories: 40,
    protein: 10,
    activeDoseG: 10,
    activeName: 'Collagen Peptides',
    actives: [{ name: 'Bovine collagen peptides', amount: 10, unit: 'g' }],
    fillersPct: 5,
    sweeteners: [],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 98,
    heavyMetalsPass: true,
    defaultPriceUSD: 30,
    timing: 'Morning / with coffee',
    howToUse: 'Stir into hot or cold liquid.',
    bestFor: ['joints/skin goals (general)'],
    avoidIf: ['expecting complete protein for hypertrophy'],
    pros: ['Clean', 'Mixes easily', 'Lab tested'],
    cons: ['Incomplete amino profile for muscle'],
  }),
  baseEntry({
    id: 'collagen-02',
    code: 'CO-02',
    name: 'Collagen Entry 02',
    brand: 'Brand TBD-F',
    category: 'collagen',
    subcategory: 'flavored',
    typeLabel: 'Collagen · Flavored beauty blend',
    icon: '✨',
    summary: 'Flavored collagen with extras — lower peptide dose, more sugar/artificials.',
    servingSizeG: 13,
    servingsPerContainer: 30,
    defaultPackageG: 390,
    calories: 48,
    protein: 9,
    carbs: 2,
    sugar: 1.5,
    addedSugar: 1.5,
    sodiumMg: 45,
    activeDoseG: 8,
    activeName: 'Collagen Peptides',
    actives: [
      { name: 'Collagen peptides', amount: 8, unit: 'g' },
      { name: 'Vitamin C', amount: 90, unit: 'mg' },
    ],
    fillersPct: 18,
    sweeteners: ['sucralose'],
    colors: ['natural flavor'],
    allergens: [],
    artificial: true,
    thirdPartyTested: false,
    defaultPriceUSD: 34,
    timing: 'Morning',
    howToUse: '1 scoop in water.',
    bestFor: [],
    avoidIf: ['want max peptides per $'],
    pros: ['Flavored', 'Added vitamin C'],
    cons: ['Less collagen', 'Sweetener', 'No lab seal'],
  }),
  baseEntry({
    id: 'collagen-03',
    code: 'CO-03',
    name: 'Marine Collagen Entry 03',
    brand: 'Brand TBD-C',
    category: 'collagen',
    subcategory: 'marine',
    typeLabel: 'Collagen · Marine peptides',
    icon: '✨',
    summary: 'Fish-sourced collagen. Fish allergen flag; typically finer peptides.',
    servingSizeG: 10,
    servingsPerContainer: 30,
    defaultPackageG: 300,
    calories: 36,
    protein: 9,
    activeDoseG: 9,
    activeName: 'Marine Collagen',
    actives: [{ name: 'Marine collagen peptides', amount: 9, unit: 'g' }],
    fillersPct: 4,
    allergens: ['fish'],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 97,
    heavyMetalsPass: true,
    defaultPriceUSD: 38,
    timing: 'Morning',
    howToUse: 'Dissolve in liquid.',
    bestFor: ['prefer marine source'],
    avoidIf: ['fish allergy'],
    pros: ['Clean', 'Lab tested'],
    cons: ['Fish allergen', 'Price'],
  }),

  // ——— PRE-WORKOUT (6) ———
  baseEntry({
    id: 'pre-01',
    code: 'PW-01',
    name: 'Pre-Workout Entry 01',
    brand: 'Brand TBD-B',
    category: 'pre',
    subcategory: 'high-stim',
    typeLabel: 'Pre · High stimulant',
    icon: '🔥',
    summary: 'High caffeine with moderate citrulline. Artificial-heavy; check stim tolerance.',
    servingSizeG: 12,
    servingsPerContainer: 25,
    defaultPackageG: 300,
    calories: 15,
    carbs: 2,
    sodiumMg: 110,
    activeDoseG: 0.35,
    activeName: 'Caffeine',
    caffeineMg: 350,
    citrullineG: 4,
    betaAlanineG: 2,
    actives: [
      { name: 'Citrulline malate', amount: 4, unit: 'g' },
      { name: 'Caffeine anhydrous', amount: 350, unit: 'mg' },
      { name: 'Beta-alanine', amount: 2, unit: 'g' },
    ],
    fillersPct: 30,
    sweeteners: ['sucralose', 'acesulfame potassium'],
    proprietaryBlend: false,
    allergens: [],
    artificial: true,
    thirdPartyTested: false,
    defaultPriceUSD: 35,
    timing: '20–30 min pre-training',
    howToUse: '1 scoop; start with ½ scoop.',
    bestFor: ['advanced stim users'],
    avoidIf: ['caffeine sensitive', 'evening training'],
    pros: ['Disclosed actives'],
    cons: ['High stim', 'Artificials', 'Citrulline only 4g'],
  }),
  baseEntry({
    id: 'pre-02',
    code: 'PW-02',
    name: 'Pre-Workout Entry 02',
    brand: 'Brand TBD-A',
    category: 'pre',
    subcategory: 'stim-free',
    typeLabel: 'Pre · Stim-free pump',
    icon: '🔥',
    summary: 'Stim-free with stronger citrulline. Better for evening sessions / caffeine cutters.',
    servingSizeG: 15,
    servingsPerContainer: 20,
    defaultPackageG: 300,
    calories: 20,
    carbs: 3,
    sodiumMg: 80,
    activeDoseG: 0,
    activeName: 'Citrulline Malate',
    caffeineMg: 0,
    citrullineG: 6,
    betaAlanineG: 2.5,
    actives: [
      { name: 'Citrulline malate', amount: 6, unit: 'g' },
      { name: 'Beta-alanine', amount: 2.5, unit: 'g' },
      { name: 'Betaine', amount: 2, unit: 'g' },
    ],
    fillersPct: 15,
    sweeteners: ['stevia'],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 96,
    heavyMetalsPass: true,
    defaultPriceUSD: 40,
    timing: '20–30 min pre-training',
    howToUse: '1 scoop.',
    bestFor: ['evening training', 'stim-avoiders'],
    avoidIf: [],
    pros: ['6g citrulline', 'Clean sweeteners', 'Lab tested'],
    cons: ['No energy from caffeine'],
  }),
  baseEntry({
    id: 'pre-03',
    code: 'PW-03',
    name: 'Pre-Workout Entry 03',
    brand: 'Brand TBD-F',
    category: 'pre',
    subcategory: 'proprietary',
    typeLabel: 'Pre · Proprietary blend',
    icon: '🔥',
    summary: 'Large proprietary blend — poor transparency. Hard to score actives fairly.',
    servingSizeG: 10,
    servingsPerContainer: 30,
    defaultPackageG: 300,
    calories: 10,
    sugar: 0,
    sodiumMg: 150,
    caffeineMg: 200,
    citrullineG: 0,
    activeDoseG: 0.2,
    activeName: 'Caffeine (est.)',
    actives: [{ name: 'Proprietary pre blend', amount: 8, unit: 'g' }],
    fillersPct: 40,
    sweeteners: ['sucralose'],
    proprietaryBlend: true,
    allergens: [],
    artificial: true,
    thirdPartyTested: false,
    defaultPriceUSD: 29,
    timing: 'Pre-training',
    howToUse: '1 scoop.',
    bestFor: [],
    avoidIf: ['want dose transparency'],
    pros: ['Cheap'],
    cons: ['Opaque formula', 'Fillers', 'Unknown citrulline'],
  }),
  baseEntry({
    id: 'pre-04',
    code: 'PW-04',
    name: 'Pre-Workout Entry 04',
    brand: 'Brand TBD-C',
    category: 'pre',
    subcategory: 'moderate-stim',
    typeLabel: 'Pre · Moderate stim',
    icon: '🔥',
    summary: 'Balanced 200mg caffeine + 5g citrulline. Reasonable everyday pre.',
    servingSizeG: 13,
    servingsPerContainer: 25,
    defaultPackageG: 325,
    calories: 15,
    sodiumMg: 95,
    caffeineMg: 200,
    citrullineG: 5,
    betaAlanineG: 2,
    activeDoseG: 0.2,
    activeName: 'Caffeine',
    actives: [
      { name: 'Citrulline malate', amount: 5, unit: 'g' },
      { name: 'Caffeine', amount: 200, unit: 'mg' },
      { name: 'Beta-alanine', amount: 2, unit: 'g' },
      { name: 'L-Tyrosine', amount: 1, unit: 'g' },
    ],
    fillersPct: 18,
    sweeteners: ['stevia', 'monk fruit'],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    labelAccuracyPct: 95,
    heavyMetalsPass: true,
    defaultPriceUSD: 38,
    timing: 'Pre-training',
    howToUse: '1 scoop.',
    bestFor: ['most trainees'],
    avoidIf: ['very stim-sensitive'],
    pros: ['Transparent', 'Solid doses', 'Clean sweeteners'],
    cons: ['Beta-alanine tingles'],
  }),

  // ——— OMEGA-3 (4) ———
  baseEntry({
    id: 'omega-01',
    code: 'OM-01',
    name: 'Omega-3 Entry 01',
    brand: 'Brand TBD-A',
    category: 'omega',
    subcategory: 'fish-oil',
    form: 'softgel',
    typeLabel: 'Omega-3 · Fish oil softgels',
    icon: '🐟',
    summary: 'Standard fish oil. Score on combined EPA+DHA, not just "1000mg fish oil".',
    servingSizeG: 2,
    servingLabel: 'per 2 softgels',
    servingsPerContainer: 60,
    defaultPackageG: 120,
    calories: 20,
    fat: 2,
    activeDoseG: 0.6,
    activeName: 'EPA+DHA',
    actives: [
      { name: 'EPA', amount: 360, unit: 'mg' },
      { name: 'DHA', amount: 240, unit: 'mg' },
    ],
    fillersPct: 10,
    allergens: ['fish'],
    artificial: false,
    thirdPartyTested: true,
    labName: 'Lab TBD',
    heavyMetalsPass: true,
    defaultPriceUSD: 22,
    timing: 'With meals',
    howToUse: '2 softgels with food.',
    bestFor: ['general omega-3 intake'],
    avoidIf: ['fish allergy'],
    pros: ['600mg EPA+DHA', 'Tested'],
    cons: ['Fish allergen', 'Softgel burden'],
  }),
  baseEntry({
    id: 'omega-02',
    code: 'OM-02',
    name: 'Omega-3 Entry 02',
    brand: 'Brand TBD-B',
    category: 'omega',
    subcategory: 'fish-oil',
    form: 'softgel',
    typeLabel: 'Omega-3 · Low-potency fish oil',
    icon: '🐟',
    summary: 'Weak EPA/DHA per softgel — easy to overpay for filler oil.',
    servingSizeG: 1,
    servingLabel: 'per softgel',
    servingsPerContainer: 90,
    defaultPackageG: 90,
    calories: 10,
    fat: 1,
    activeDoseG: 0.25,
    activeName: 'EPA+DHA',
    actives: [
      { name: 'EPA', amount: 150, unit: 'mg' },
      { name: 'DHA', amount: 100, unit: 'mg' },
    ],
    fillersPct: 25,
    allergens: ['fish'],
    artificial: false,
    thirdPartyTested: false,
    defaultPriceUSD: 15,
    timing: 'With meals',
    howToUse: '1–3 softgels; check total EPA+DHA.',
    bestFor: [],
    avoidIf: ['want potent omega-3'],
    pros: ['Cheap sticker price'],
    cons: ['Low potency', 'No lab seal'],
  }),
  baseEntry({
    id: 'omega-03',
    code: 'OM-03',
    name: 'Algae Omega Entry 03',
    brand: 'Brand TBD-C',
    category: 'omega',
    subcategory: 'algae',
    form: 'softgel',
    typeLabel: 'Omega-3 · Algae oil (vegan)',
    icon: '🐟',
    summary: 'Vegan DHA-forward algae oil. Fish-allergen free.',
    servingSizeG: 1,
    servingLabel: 'per softgel',
    servingsPerContainer: 60,
    defaultPackageG: 60,
    calories: 10,
    fat: 1,
    activeDoseG: 0.4,
    activeName: 'EPA+DHA',
    actives: [
      { name: 'DHA', amount: 300, unit: 'mg' },
      { name: 'EPA', amount: 100, unit: 'mg' },
    ],
    fillersPct: 12,
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    heavyMetalsPass: true,
    defaultPriceUSD: 28,
    timing: 'With meals',
    howToUse: '1 softgel.',
    bestFor: ['vegan', 'fish-allergic'],
    avoidIf: [],
    pros: ['Vegan', 'No fish allergen', 'Tested'],
    cons: ['Price per mg'],
  }),

  // ——— MULTIVITAMINS (4) ———
  baseEntry({
    id: 'multi-01',
    code: 'MV-01',
    name: 'Multivitamin Entry 01',
    brand: 'Brand TBD-A',
    category: 'multi',
    subcategory: 'daily',
    form: 'capsule',
    typeLabel: 'Multi · Daily capsule',
    icon: '💊',
    summary: 'Straightforward daily multi. Low sugar, disclosed actives, minimal artificial colors.',
    servingSizeG: 1,
    servingLabel: 'per 2 capsules',
    servingsPerContainer: 30,
    defaultPackageG: 60,
    calories: 5,
    sugar: 0,
    addedSugar: 0,
    sodiumMg: 5,
    activeDoseG: 0,
    activeName: 'Vitamin & mineral blend',
    actives: [
      { name: 'Vitamin D3', amount: 25, unit: 'mcg' },
      { name: 'Vitamin B12', amount: 6, unit: 'mcg' },
      { name: 'Zinc', amount: 11, unit: 'mg' },
      { name: 'Magnesium', amount: 50, unit: 'mg' },
    ],
    fillersPct: 20,
    sweeteners: [],
    colors: [],
    allergens: [],
    artificial: false,
    thirdPartyTested: true,
    defaultPriceUSD: 20,
    timing: 'Morning with food',
    howToUse: '2 capsules daily.',
    bestFor: ['coverage gaps'],
    avoidIf: [],
    pros: ['Clean', 'Tested'],
    cons: ['Magnesium dose modest'],
  }),
  baseEntry({
    id: 'multi-02',
    code: 'MV-02',
    name: 'Multivitamin Gummy Entry 02',
    brand: 'Brand TBD-F',
    category: 'multi',
    subcategory: 'gummy',
    form: 'gummy',
    typeLabel: 'Multi · Gummies',
    icon: '💊',
    summary: 'Gummy multis often add sugar and skip key minerals — score accordingly.',
    servingSizeG: 6,
    servingLabel: 'per 2 gummies',
    servingsPerContainer: 45,
    defaultPackageG: 270,
    calories: 30,
    carbs: 6,
    sugar: 5,
    addedSugar: 5,
    activeDoseG: 0,
    activeName: 'Vitamin blend',
    actives: [
      { name: 'Vitamin C', amount: 45, unit: 'mg' },
      { name: 'Vitamin D', amount: 10, unit: 'mcg' },
    ],
    fillersPct: 50,
    sweeteners: ['sugar', 'glucose syrup'],
    colors: ['artificial color'],
    allergens: [],
    artificial: true,
    thirdPartyTested: false,
    defaultPriceUSD: 18,
    timing: 'Daily',
    howToUse: '2 gummies.',
    bestFor: [],
    avoidIf: ['low sugar preference'],
    pros: ['Easy to take'],
    cons: ['Sugar', 'Incomplete mineral coverage', 'Artificial colors'],
  }),
  baseEntry({
    id: 'multi-03',
    code: 'MV-03',
    name: 'Multivitamin Entry 03',
    brand: 'Brand TBD-D',
    category: 'multi',
    subcategory: 'athlete',
    form: 'tablet',
    typeLabel: 'Multi · Athlete formula',
    icon: '💊',
    summary: 'Higher-dose athlete multi. Watch megadoses and proprietary blends.',
    servingSizeG: 3,
    servingLabel: 'per 3 tablets',
    servingsPerContainer: 30,
    defaultPackageG: 90,
    calories: 10,
    sodiumMg: 15,
    activeDoseG: 0,
    activeName: 'Athlete vitamin matrix',
    actives: [
      { name: 'Vitamin D3', amount: 50, unit: 'mcg' },
      { name: 'Zinc', amount: 30, unit: 'mg' },
      { name: 'Magnesium', amount: 200, unit: 'mg' },
      { name: 'Proprietary antioxidant blend', amount: 200, unit: 'mg' },
    ],
    fillersPct: 22,
    proprietaryBlend: true,
    sweeteners: [],
    allergens: ['soy'],
    artificial: false,
    thirdPartyTested: true,
    defaultPriceUSD: 32,
    timing: 'With breakfast',
    howToUse: '3 tablets with food.',
    bestFor: ['high training volume'],
    avoidIf: ['soy allergy'],
    pros: ['More magnesium', 'Tested'],
    cons: ['Pill burden', 'Some proprietary blend', 'Soy'],
  }),
];

/** Exchange rate for mock local pricing until currency table exists in Supabase */
const USD_TO_INR = 83;

/** Export shape the API layer expects */
const MOCK_DB = {
  categories: CATEGORIES,
  brands: BRAND_PLACEHOLDERS,
  supplements: CATALOG,
};
